# Generated by Django 4.2.3 on 2023-07-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("flag", models.CharField(max_length=20)),
                ("population", models.IntegerField()),
                ("gdp", models.DecimalField(decimal_places=2, max_digits=100)),
                (
                    "internal_debt",
                    models.DecimalField(decimal_places=2, max_digits=100),
                ),
                (
                    "external_debt",
                    models.DecimalField(decimal_places=2, max_digits=100),
                ),
                (
                    "continent",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("asia", "Asia"),
                            ("africa", "Africa"),
                            ("north_america", "North America"),
                            ("south_america", "South America"),
                            ("europe", "Europe"),
                            ("australia", "Australia"),
                        ],
                        default="",
                        max_length=13,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("asia", "Asia"),
                            ("africa", "Africa"),
                            ("north_america", "North America"),
                            ("south_america", "South America"),
                            ("europe", "Europe"),
                            ("australia", "Australia"),
                            ("caribbean", "Caribbean"),
                            ("central_america", "Central America"),
                            ("oceania", "Oceania"),
                        ],
                        default="",
                        max_length=15,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Countries",
                "ordering": ("pk",),
            },
        ),
    ]
