# Generated by Django 4.2.3 on 2023-07-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("countries", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="chart_link",
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="country",
            name="extra_link",
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="country",
            name="source_link",
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
