# Generated by Django 4.2.4 on 2023-09-03 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_country_chart_link_country_extra_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='GDPTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gdp1', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('gdp2', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('gdp3', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('gdp4', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('gdp5', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('gdp6', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('gdp7', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('gdp8', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('gdp9', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('gdp10', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('gdp11', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('gdp12', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('gdp13', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('gdp14', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('gdp15', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.country')),
            ],
        ),
    ]
